### ISSUE TITLE
We need a way to guarantee debugging code is called.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#166] opened 2013-10-01 21:30 UTC
If one defines an external function to record information for debugging and the Func it is called within is scheduled compute_root, but the root result is not used anywhere, the external function will never be called. It is a productivity drain to have to ensure the result is used somehow. (I.e. yes, one can always make it work, but new users struggle to understand why things failed and experienced users wish they didn't have to think about this.)

Two possible solutions:
- A compute_debug() or compute_always() scheduling primitive, which is like compute_root, but asserts the result is used. (The difference in naming being one of intent. Is there ever any use for this outside debugging? That likely depends on the answer to the other proposed solution.)
- A way to mark an external function as required to be called. I'm not sure how I feel about this as it relates to whether external functions are really pure, and I feel they generally should be. SO I can easily see this getting too messy to be something we want to do, but if there is a clean and sensible definition, it might be useful outside of debugging as well.

**Comment by dsharletg** [comment] 2021-07-14 03:01
Duplicate of #2931 (which has more discussion).

**Closed by dsharletg** 2021-07-14 03:01 UTC
Labels: enhancement
