### ISSUE TITLE
A crash related to vectorization in a Skylake CPU (AVX-512) when a buffer is larger than a certain size and non-power-of 2

### ISSUE THREAD

**Issue by liwchang** [halide/Halide#3287] opened 2018-09-26 19:00 UTC
Build 7/22/2018 Win64
Crash only happens on Skylake CPU.

Simple unit test:
int size = 4096 + 2048 + 1024 - 2;
Halide::Buffer<float> input({ size }, "input");
Halide::Func func1;
Halide::Func func2;
Halide::Var x;
func1(x) = input(x) + 1.0f;
func1.compute_root();
func2(x) = func1(x) + 1.0f;
func2.compute_root().vectorize(x, 16, Halide::TailStrategy::GuardWithIf);

If size is power of 2, it will work.
If func2 is not vectorized, it will also work.
If func1 is vectorized, and func2 is not, it still crashs.

**Comment by amitaga** [comment] 2018-09-27 18:48
This seems to be very basic issue with vectorization for AVX512. Can someone please suggest a solution or a workaround?

**Comment by zvookin** [comment] 2018-09-27 20:12
This code embeds a buffer in the generated code -- that is input is not
passed as a parameter. My guess is we do not guarantee adequate alignment
in this case. I though I fixed a bug with this recently, but I will look
into it and should have something shortly if it is still an issue. The work
around is to not embed the buffer -- e.g. make it an ImageParam and pass it
to the realize call.

-Z-

**Comment by liwchang** [comment] 2018-09-27 20:44
Great, let me try the latest again.
Maybe it is already solved.

**Comment by zvookin** [comment] 2018-09-27 21:15
If the compilation is ahead of time, I think I see the bug. (For JIT, we
likely don't embed the buffer.) A little more investigation is needed, but
I can probably have a PR open today if it is what I think it is.

-Z-

**Comment by amitaga** [comment] 2018-09-27 21:33
Thanks Zalman. I am seeing this with JIT.

**Comment by zvookin** [comment] 2018-09-28 20:20
I have not been able to reproduce a failure, but opened
https://github.com/halide/Halide/pull/3295 which may be the fix. (And seems
like an increase in correctness in any event.)

-Z-

**Comment by liwchang** [comment] 2018-09-28 20:29
@zvookin. 
I tried the latest version. (My build was somewhere end of this July)
It seems working correctly now.
I will update version next time before reporting a issue. 
Thanks a lot.

**Comment by zvookin** [comment] 2018-09-29 01:48
Sounds like the JIT case was fixed by updating to recent Halide. I just merged a fix for the AOT case.

**Closed by zvookin** 2018-09-29 01:48 UTC
