### ISSUE TITLE
Internal error: Condition failed: rest.defined(), Block of undefined

### ISSUE THREAD

**Issue by bleibig** [halide/Halide#1578] opened 2016-10-27 01:39 UTC
See this test case:

``` cpp
#include "Halide.h"

using namespace Halide;

Var x("x"), y("y");

int main() {
    ImageParam table(Int(32), 1, "table");

    Func f("f"), g("g"), h("h");

    f(x, y) = x*2 + y;
    g(x, y) = x + y*2;
    h(x, y) = select(table(42) == 0, f(x, y), g(x, y));

    f.compute_root();
    g.compute_root();
    h.compute_root().gpu_tile(x, y, 8, 8);

    Target t = get_host_target();
    t.set_feature(Target::OpenCL);

    h.compile_to_file("generated", h.infer_arguments(), "generated", t);

    return 0;
}
```

Compiling gives this error:

```
Internal error at /Users/brian/src/Halide/src/IR.cpp:447 triggered by user code at ./generate.cpp:23:
Condition failed: rest.defined()
Block of undefined
```

Some notes from investigating:
- The error happens in the InjectHostDevBufferCopies phase.
- The error only happens with the combination of f and/or g being compute_root(), and the select condition looking up a value in an ImageParam. If f and g are inline or the condition is looking at a regular Param, the error does not occur.
- This happens for any GPU codegen, not just OpenCL.

Also, #1549 is happening with the error coming from the same file with GPU codegen enabled as well, could it be related?

**Comment by abadams** [comment] 2016-10-27 16:12
Root cause: f is only computed if table(42) is zero, and g is only computed
if table(42) is non-zero. f and g should only have host_dirty set if they
were computed, so the host_dirty calls were correctly inside the true
clause. but InjectHostBufferCopies wasn't handling IfThenElse nodes that
didn't have an else case.

Fixed in 6e3b7be141c508cc877d69c0a36f4c9cd8df787d

**Comment by bleibig** [comment] 2016-10-27 18:51
Thank you for the quick turnaround. However this ended up revealing another issue. Here's a slightly modified test case:

```cpp
#include "Halide.h"

using namespace Halide;

Var x("x"), y("y");

int main() {
    ImageParam table(Int(32), 1, "table");

    Func f("f"), g("g"), h("h");

    f(x, y) = x*2 + y + table(x);
    g(x, y) = x + y*2 + table(y);
    h(x, y) = select(table(42) == 0, f(x, y), g(x, y));

    f.compute_root().gpu_tile(x, y, 8, 8);
    g.compute_root().gpu_tile(x, y, 8, 8);
    h.compute_root().gpu_tile(x, y, 8, 8);

    Target t = get_host_target();
    t.set_feature(Target::OpenCL);

    h.compile_to_file("generated", h.infer_arguments(), "generated", t);

    return 0;
}
```

The changes are that f and g are now both computed on the GPU, and they read from table in their definition. It's causing this error now:

```
Internal error at /Users/brian/src/Halide/src/InjectHostDevBufferCopies.cpp:303 triggered by user code at ./generate.cpp:23:
Condition failed: !device_read && !device_wrote
```

It looks like since table is being read from both the device (from the implementation) and the host (for the if statement) for f and g, it is causing another unexpected issue in InjectHostDevBufferCopies.

**Comment by abadams** [comment] 2016-10-27 21:05
We were assuming that a buffer is only ever read on the device XOR on the
host in any block of code, but lifting the table read out into the if
statement means that it's read on host AND device in this piece of code. So
your diagnosis is correct. I think the behavior is safe, because neither
side is writing to it. I've adjusted the assert accordingly in PR #1584

@zvookin does this make sense to you?

**Comment by zvookin** [comment] 2017-09-01 22:18
Both test cases seem to compile now.

**Closed by zvookin** 2017-09-01 22:18 UTC
