### ISSUE TITLE
.gitignore could use some gardening

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4648] opened 2020-02-26 18:39 UTC
Our toplevel .gitignore has accreted many inscrutable entries over time; this is probably mostly benign, but after the CMake changes (https://github.com/halide/Halide/pull/4644) lands, might be good to revisit and see if it can be pruned into something more sensible.

**Comment by alexreinking** [comment] 2020-08-09 23:41
Duplicate of #1137

**Closed by alexreinking** 2020-08-09 23:41 UTC
Labels: enhancement
