### ISSUE TITLE
All Halide programs crash with trunk LLVM (on Windows)

### ISSUE THREAD

**Issue by yongyi781** [halide/Halide#620] opened 2015-01-09 04:28 UTC
I just updated to the trunk LLVM, version 3.6, and recompiled everything in Release mode on Windows with the same settings as in the Windows build script. Every program is now crashing with the following output:

Assertion failed: RealOffset <= INT32_MAX && RealOffset >= INT32_MIN, file C:\Us
ers\Yongyi\Documents\GitHub\Halide\llvm\lib\ExecutionEngine\RuntimeDyld\RuntimeD
yldELF.cpp, line 271

**Comment by abadams** [comment] 2015-01-09 04:51
The nightly build on Windows was happy last night with trunk llvm. Let's
see if it works tonight...

**Comment by abadams** [comment] 2015-01-09 16:43
Worked last night with llvm r225518 in visual studio 2013. Perhaps try nuking your build folders and retrying? I often find that if the build gets into a funny state that fixes it.

**Comment by yongyi781** [comment] 2015-01-09 21:31
I'm also on Windows 8.1, if that helps. I looked into the LLVM source code file; it seems like the switch for the ELF type is branching into case ELF::R_X86_64_PC32 instead of case ELF::R_X86_64_PC64.

**Comment by yongyi781** [comment] 2015-01-09 21:47
Aha! I think this makes sense. On Windows 7 64-bit, addresses of executables and objects in memory are usually within INT_MAX, but Windows 8.1 changes the way this works and they are now usually greater than INT_MAX.

**Comment by yongyi781** [comment] 2015-01-10 01:29
Oh, clarification: This only happens with JIT compilation.

**Comment by abadams** [comment] 2015-01-10 01:34
I figured, what with the ELF usage. It's looking like we're going to need a
windows 8.1 build bot :(

**Comment by yongyi781** [comment] 2015-01-13 01:09
So I just turned LLVM_ENABLE_ASSERTIONS off, and it works. The assert was somehow superfluous??

**Comment by abadams** [comment] 2015-01-13 01:20
Perhaps the bad relocation wasn't for a symbol we end up using.

**Comment by yongyi781** [comment] 2015-01-13 01:24
Argh, I just ran the Halide tests and some of them succeed and some crash due to an access violation somewhere. Perhaps it's not so simple after all. Of the first few correctness tests, argmax passes, assertion_failure_in_parallel_for crashes, autotune_bug_1 passes, autotune_bug_2, 3, and 4 crash, and autotune_bug_5 passes.

**Comment by yongyi781** [comment] 2015-01-14 03:02
How's the windows 8.1 built bot going?

**Comment by abadams** [comment] 2015-01-14 03:04
It's unlikely to happen any time soon. This sounds like an llvm bug that we
can't easily work around, so hopefully the llvm guys will fix it at some
stage.

**Comment by yongyi781** [comment] 2015-01-14 03:47
It seems like all the LLVM tests pass on my computer.

**Comment by abadams** [comment] 2015-01-14 06:20
I don't doubt it, but generating valid or invalid relocations is way below
the interface LLVM provides - we just give it bitcode. LLVM jitting on
Windows is weird. For one thing, it uses ELF object files where static
compilation uses COFF files. ELF isn't exactly a native format on windows.

Perhaps the tests aren't run in processes large enough to have a breaking
memory layout.

**Comment by yongyi781** [comment] 2015-01-14 12:49
I should try compiling Halide in 32-bit (!) to see if that avoids the problem.

**Comment by yongyi781** [comment] 2015-01-14 18:43
32-bit Halide works on Windows 8.1! Yay!

**Comment by abadams** [comment] 2015-03-25 16:46
We now have a Windows 8.1 build bot, and I'm reproducing the issue with 64-bit pnacl llvm (based on llvm 3.6) but not trunk llvm, so looks like it has been fixed in trunk. It's a bit weird to use pnacl llvm for jitting on Windows, so I'll mark this issue as fixed.

**Closed by abadams** 2015-03-25 16:46 UTC

**Comment by alemoi** [comment] 2015-08-15 21:20
Hi there! Do you know if this issue is reproducible with LLVM 3.7.0 RC? Thank you for the answer!

**Comment by abadams** [comment] 2015-08-15 21:28
llvm trunk works fine, and if I recall correctly the issue was fixed before
the llvm 3.7 was cut, so it should be OK.

**Comment by alemoi** [comment] 2015-08-15 21:35
Thank you for the immediate answer! I will check 3.7.0 which is about to be released.
