### ISSUE TITLE
random fuzz_simplify error

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#2949] opened 2018-05-10 01:08 UTC
Found during unrelated testing:

```
Simplify fuzz test seed: 1525913331
a = -85
b = int32(a)
c = int32(c)
d = int32(a)
e = int32(a)
(((-67*120)*(-73 + int32(a)))/69)
(((int32(a)*2680) + -195640)/-23)
In vector lane 0:
(((-67*120)*(-73 + int32(a)))/69) -> 18410
(((int32(a)*2680) + -195640)/-23) -> 18411
../halide/Makefile:1484: recipe for target 'correctness_fuzz_simplify' failed
```

**Comment by steven-johnson** [comment] 2018-05-10 01:09
(on arm32)

**Comment by psuriana** [comment] 2018-05-14 16:51
The bug is caused by division of negative gcd (https://github.com/halide/Halide/blob/master/src/Simplify.cpp#L2251), e.g. `-3*(a+5)/6` simplified into `(-a-5)/2` and `(a+5)/(-2)` will produce different result, since the rounding rules are different for negative/positive denominator. Apparently, this bug should be fixed in the new simplifier PR (it has been removed in the new PR).

**Comment by dsharletg** [comment] 2021-07-14 03:05
This isn't happening currently for this seed (but maybe the RNG or expression generation changed...).

**Closed by dsharletg** 2021-07-14 03:05 UTC
