### ISSUE TITLE
Halide on the Hexagon on a Snapdragon 835 : blur app aborts

### ISSUE THREAD

**Issue by markivx** [halide/Halide#3608] opened 2019-01-23 20:23 UTC
Hello, I'm trying to run the blur example on a hexagon DSP on a Snapdragon 835. Compilation went okay, but the halide_blur() call dies somewhere and the test app aborts. All I see is a message "Aborted". mini-dm didn't provide any information either. (I have testsig setup correctly too, other Hexagon SDK samples work)

```
$ HL_TARGET=arm-64-android-hvx_128 ./adb_run_on_device.sh

g++ -std=c++11 -I ../../distrib/include/ -I ../../distrib/tools/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi -fno-rtti halide_blur_generator.cpp ../../distrib/lib/libHalide.a ../../distrib/tools/GenGen.cpp -o bin/halide_blur.generator  -ldl -lpthread -lz -lz -lrt -ldl -lpthread -lm -lxml2

bin/halide_blur.generator -g halide_blur -o ./bin/arm-64-android target=arm-64-android-hvx_64

/home/markiv/ndk-r10d-toolchain/bin/aarch64-linux-android-c++ -std=c++11 -I ../../distrib/include/ -I ../../distrib/tools/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi -fno-rtti -fopenmp -Wall -O2 -I./bin/arm-64-android test.cpp ./bin/arm-64-android/halide_blur.a -o bin/arm-64-android/test -llog -fPIE -pie

rm bin/arm-64-android/halide_blur.a

../../src/runtime/hexagon_remote/bin/arm-64-android/libhalide_hexagon_host.so: 1 file pushed. 4.3 MB/s (28000 bytes in 0.006s)

../../src/runtime/hexagon_remote/bin/v60/signed_by_debug/libhalide_h...agon_remote_skel.so: 1 file pushed. 6.0 MB/s (38780 bytes in 0.006s)
bin/arm-64-android/test: 1 file pushed. 17.9 MB/s (4235119 bytes in 0.226s)
Aborted 
```

**Comment by dsharletg** [comment] 2019-01-24 05:18
What do you see if you do `adb logcat | grep halide` ?

**Comment by dsharletg** [comment] 2019-04-30 06:26
I'm going to close this, if you are still seeing the issue and can get back to us with the output of adb, feel free to reopen.

**Closed by dsharletg** 2019-04-30 06:26 UTC

**Comment by dgajaria-ADI** [comment] 2019-07-17 20:11
I am using Intrinsyc Open-Q 835 Snapdragon Dev platform with Android Nougat (7.1.2), I get the same error (App Aborts) when trying to launch blur App. 

Output of ```adb logcat | grep halide``` is as below
```
07-17 19:40:49.935 27848 27848 I halide  : Hexagon: remote_poll_log failed 59
07-17 19:40:49.935 27848 27848 I halide  : Error: Initialization of Hexagon kernels failed 
```

**Comment by dsharletg** [comment] 2019-07-17 20:17
What do you see if you do `adb logcat | grep dsp`? Is there a message about 'signature verify'? If so, the issue is likely that the Hexagon code is not signed, and there is no 'testsig' on the device (see Hexagon SDK docs).

Also, Android N is 3-4 years old, and I remember some extra challenges in using FastRPC around that time. Is it possible to update to a newer version of Android?

**Comment by dgajaria-ADI** [comment] 2019-07-17 22:07
I generated the testsig signature using the testsig.py script (provided with Hexagon SDK) and pushed it to android device. I still get the same error. Output of ```adb logcat | grep dsp``` is as follow
```
07-17 21:53:08.230  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:916: /dsp/fastrpc_shell_3 load failed 69, searching...                                                    
07-17 21:53:08.230  3772  3772 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:691:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)                                    
07-17 21:53:08.230  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:930: open_shell failed. domain 69                                                                         
07-17 21:53:08.230  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1048: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory
07-17 21:53:08.230  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1128: Error ffffffff: open dev -1 for domain 3 failed
07-17 21:53:08.230  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:916: /dsp/fastrpc_shell_3 load failed 69, searching...
07-17 21:53:08.231  3772  3772 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:691:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:930: open_shell failed. domain 69
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1048: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1128: Error ffffffff: open dev -1 for domain 3 failed
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:576: Error 3b: remote handle invoke failed. domain 3, handle ffffffff, sc 30100, pra 0x7ff9172860
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:916: /dsp/fastrpc_shell_3 load failed 69, searching...
07-17 21:53:08.231  3772  3772 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:691:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)                                    
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:930: open_shell failed. domain 69                                                                         
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1048: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory                     
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1128: Error ffffffff: open dev -1 for domain 3 failed                                                     
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:916: /dsp/fastrpc_shell_3 load failed 69, searching...                                                    
07-17 21:53:08.231  3772  3772 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:691:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)                                    
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:930: open_shell failed. domain 69                                                                         
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1048: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory                     
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1128: Error ffffffff: open dev -1 for domain 3 failed                                                     
07-17 21:53:08.231  3772  3772 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:576: Error 3b: remote handle invoke failed. domain 3, handle ffffffff, sc 6010200, pra 0x7ff9172430 
```

**Comment by dsharletg** [comment] 2019-07-18 06:43
If you are still seeing the signature verification error, you may simply need to reboot the device after installing the testsig.

If that doesn't fix the issue, I think you'll need some support from Qualcomm to resolve this. @pranavb-ca @dpalermo

**Comment by dgajaria-ADI** [comment] 2019-07-18 14:26
Thanks @dsharletg. I tried rebooting and it did not help. 

On checking if FastRPC is operational using ```adb logcat -s adsprpc```, I got the following output
```
--------- beginning of system
--------- beginning of main
--------- beginning of crash
```
Does that mean FastRPC is crashing?

Android Oreo 8.1 is available for board, I may try updating the board.

**Comment by dgajaria-ADI** [comment] 2019-07-18 19:19
Updated to Android Oreo, still getting same error.

Running the ```logcat | grep test``` shows the following log
```
03-20 15:10:28.026 17034 17034 V /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1011: /dsp/fastrpc_shell_3 load failed 45, searching...                   
03-20 15:10:28.027 17034 17034 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:695:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)    
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1029: open_shell failed. domain 69                                        
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1151: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory                                                                                                                                                                                   
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1234: Error ffffffff: open dev -1 for domain 3 failed                     
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:663: Error 2c: remote handle invoke failed. domain -1544594464, handle ffffffff, sc 30100, pra 0x7fea08ca00                                                                                                                                                             
03-20 15:10:28.027 17034 17034 V /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1011: /dsp/fastrpc_shell_3 load failed 45, searching...                   
03-20 15:10:28.027 17034 17034 E /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:695:Error 45: fopen failed for fastrpc_shell_3. (No such file or directory)    
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1029: open_shell failed. domain 69                                        
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1151: Error ffffffff: apps_dev_init failed. domain 3, errno No such file or directory                                                                                                                                                                                   
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1234: Error ffffffff: open dev -1 for domain 3 failed                     
03-20 15:10:28.027 17034 17034 D /data/local/tmp/blur/test: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:663: Error 2c: remote handle invoke failed. domain -368523776, handle ffffffff, sc 6010200, pra 0x7fea08c5d0  
```

**Comment by dgajaria-ADI** [comment] 2019-07-25 21:29
Need help to resolve the issue.

I get similar errors as above with Hexagon SDK calculator example with CDSP_FLAG=1, however I am able to run Hexagon SDK example with ADSP_FLAG=1. 

I tried doing something similar with Halide Example by setting CDSP_FLAG=0 ```export CDSP_FLAG=0```, but I still get same errors.

Tried running in debug mode and capturing log message using ```adb logcat | grep halide```, get the following
```
07-25 21:18:54.793  3344  3344 I halide  : Hexagon: halide_hexagon_initialize_kernels (user_context: 0x0, state_ptr: 0xde395e700, *state_ptr: 0x0, code: 0xde3922520, code_size: 8752)                                                          
07-25 21:18:54.793  3344  3344 I halide  : , code: 0xde3924760, code_size: 90792)                                      
07-25 21:18:54.793  3344  3344 I halide  :     Initializing shared runtime                                            
07-25 21:18:54.793  3344  3344 I halide  :     Writing shared object 'libhalide_shared_runtime.so'                      
07-25 21:18:54.794  3344  3344 I halide  :     failed to write shared object to 'libhalide_shared_runtime.so'           
07-25 21:18:54.794  3344  3344 I halide  :     halide_remote_load_library(libhalide_shared_runtime.so) ->               
07-25 21:18:54.795  3344  3344 I halide  : Hexagon: remote_poll_log failed 44                                           
07-25 21:18:54.795  3344  3344 I halide  :         44                                                                   
07-25 21:18:54.795  3344  3344 I halide  : Error: Initialization of Hexagon kernels failed
07-25 21:18:54.776  3344  3344 W test    : type=1400 audit(0.0:48): avc: denied { associate } for name="libhalide_shared_runtime.so" scontext=u:object_r:rootfs:s0 tcontext=u:object_r:labeledfs:s0 tclass=filesystem permissive=0   
```

**Comment by degot88** [comment] 2019-09-20 08:07
@dgajaria-ADI hi ! did you manage to resolve this issue? i have quite similar situation right there

**Comment by dgajaria-ADI** [comment] 2019-10-08 20:10
> @dgajaria-ADI hi ! did you manage to resolve this issue? i have quite similar situation right there

No I was not able to resolve this issue, please let me know if you have any success

**Comment by pranavb-ca** [comment] 2019-10-08 23:16
Depending on the device you are using you might need to install a testsig on your device. See Tools_Signing.html in the SDK documentation.

**Comment by degot88** [comment] 2019-10-09 10:48
I did not run test example from repository, but my own Mk file, however i eventually made it work.
I don't remember what was exactly the problem, but i believe i just accurately repeated the steps described in tutorials (from QC web site). I signed device with testsig as mentioned above, not separate libraries. Make sure you pushed everything in right places, libraries are linking well, and your code is correct (in my case i believe it was not, because i was not running prepared example)

**Comment by dgajaria-ADI** [comment] 2019-10-10 02:41
Thanks @pranavb-ca and @degot88 . I will try again. I had given up on it after trying on two different dev boards Intrinsyc 835 and Inforce 820. I was generating and pushing the testsig as per Qualcomm Hexagon SDK document, but was not successful in running Halide Hexagon DSP code. I was able to run Qualcomm SDK calculator example with ADSP flag as 1.

Could you please give me details about the dev board you are using with Halide.

**Comment by pranavb-ca** [comment] 2019-10-10 16:02
d

> Need help to resolve the issue.
> 
> I get similar errors as above with Hexagon SDK calculator example with CDSP_FLAG=1, however I am able to run Hexagon SDK example with ADSP_FLAG=1.
> 
> I tried doing something similar with Halide Example by setting CDSP_FLAG=0 `export CDSP_FLAG=0`, but I still get same errors.
> 
> Tried running in debug mode and capturing log message using `adb logcat | grep halide`, get the following
> 
> ```
> 07-25 21:18:54.793  3344  3344 I halide  : Hexagon: halide_hexagon_initialize_kernels (user_context: 0x0, state_ptr: 0xde395e700, *state_ptr: 0x0, code: 0xde3922520, code_size: 8752)                                                          
> 07-25 21:18:54.793  3344  3344 I halide  : , code: 0xde3924760, code_size: 90792)                                      
> 07-25 21:18:54.793  3344  3344 I halide  :     Initializing shared runtime                                            
> 07-25 21:18:54.793  3344  3344 I halide  :     Writing shared object 'libhalide_shared_runtime.so'                      
> 07-25 21:18:54.794  3344  3344 I halide  :     failed to write shared object to 'libhalide_shared_runtime.so'           
> 07-25 21:18:54.794  3344  3344 I halide  :     halide_remote_load_library(libhalide_shared_runtime.so) ->               
> 07-25 21:18:54.795  3344  3344 I halide  : Hexagon: remote_poll_log failed 44                                           
> 07-25 21:18:54.795  3344  3344 I halide  :         44                                                                   
> 07-25 21:18:54.795  3344  3344 I halide  : Error: Initialization of Hexagon kernels failed
> 07-25 21:18:54.776  3344  3344 W test    : type=1400 audit(0.0:48): avc: denied { associate } for name="libhalide_shared_runtime.so" scontext=u:object_r:rootfs:s0 tcontext=u:object_r:labeledfs:s0 tclass=filesystem permissive=0   
> ```

Hi @dgajaria-ADI  - Can you please give me more information
1) Which device is this?
2) Are you building Halide from this github repository or are you using Halide from inside the Hexagon SDK?

**Comment by dgajaria-ADI** [comment] 2019-10-10 20:24
> d
> 
> > Need help to resolve the issue.
> > I get similar errors as above with Hexagon SDK calculator example with CDSP_FLAG=1, however I am able to run Hexagon SDK example with ADSP_FLAG=1.
> > I tried doing something similar with Halide Example by setting CDSP_FLAG=0 `export CDSP_FLAG=0`, but I still get same errors.
> > Tried running in debug mode and capturing log message using `adb logcat | grep halide`, get the following
> > ```
> > 07-25 21:18:54.793  3344  3344 I halide  : Hexagon: halide_hexagon_initialize_kernels (user_context: 0x0, state_ptr: 0xde395e700, *state_ptr: 0x0, code: 0xde3922520, code_size: 8752)                                                          
> > 07-25 21:18:54.793  3344  3344 I halide  : , code: 0xde3924760, code_size: 90792)                                      
> > 07-25 21:18:54.793  3344  3344 I halide  :     Initializing shared runtime                                            
> > 07-25 21:18:54.793  3344  3344 I halide  :     Writing shared object 'libhalide_shared_runtime.so'                      
> > 07-25 21:18:54.794  3344  3344 I halide  :     failed to write shared object to 'libhalide_shared_runtime.so'           
> > 07-25 21:18:54.794  3344  3344 I halide  :     halide_remote_load_library(libhalide_shared_runtime.so) ->               
> > 07-25 21:18:54.795  3344  3344 I halide  : Hexagon: remote_poll_log failed 44                                           
> > 07-25 21:18:54.795  3344  3344 I halide  :         44                                                                   
> > 07-25 21:18:54.795  3344  3344 I halide  : Error: Initialization of Hexagon kernels failed
> > 07-25 21:18:54.776  3344  3344 W test    : type=1400 audit(0.0:48): avc: denied { associate } for name="libhalide_shared_runtime.so" scontext=u:object_r:rootfs:s0 tcontext=u:object_r:labeledfs:s0 tclass=filesystem permissive=0   
> > ```
> 
> Hi @dgajaria-ADI - Can you please give me more information
> 
> 1. Which device is this?
> 2. Are you building Halide from this github repository or are you using Halide from inside the Hexagon SDK?

Hi @pranavb-ca, 

The above error message was on[ Intrinsyc 835 Dev board](https://www.intrinsyc.com/snapdragon-embedded-development-kits/open-q-835-usom-development-kit/). 

I get the above error with both, Halide from github repo and also Halide library included with Hexagon SDK.

**Comment by dsharletg** [comment] 2019-10-10 20:53
> I was able to run Qualcomm SDK calculator example with ADSP flag as 1.

Can you run this example on the CDSP? In the past we had problems where the CDSP was not turned on by default, maybe this is happening here?

**Comment by dgajaria-ADI** [comment] 2019-10-10 22:56
> Note: I have made change to Makefile to target arm-64-android-hvx_128 instead of arm-64-android.
> 
> ```
> -       $^ -g halide_blur -e $(GENERATOR_OUTPUTS) -o $(@D) target=$* 
> +       $^ -g halide_blur -e $(GENERATOR_OUTPUTS) -o $(@D) target=$(HL_TARGET)   
> ```

[Source Link ](https://github.com/halide/Halide/blob/836981e16b8135f41d5a89ccf427165af3600565/apps/blur/Makefile#L11)

I compile and run it as 
```
HL_TARGET=arm-64-android-hvx_128 ./adb_run_on_device.sh 
```

Is this correct, if i don't do the above change to makefile, it compiles for arm-64-android and runs the CPU scheduler, does not run DSP scheduler. Hence I changed target to be HL_TARGET
