### ISSUE TITLE
We are missing a CMake example for Android target

### ISSUE THREAD

**Issue by piotrklos-tcl** [halide/Halide#5399] opened 2020-10-23 14:55 UTC
The section
https://github.com/halide/Halide/blob/master/README_cmake.md#use-externalproject-directly
gives some idea of what is needed to use Halide in a project that targets Android and uses CMake.

But it's a big hurdle to actually do this. Can you provide a HelloWorld example in the apps folder for this scenario?

I'm a library developer and I'm not interested and not able to read Gradle files, only CMake/make. I think that this is quite a common case because a lot of people using Halide are going to be library developers as opposed to app developers.

**Comment by steven-johnson** [comment] 2020-10-23 17:07
Yeah, Gradle is pretty obscure to read if you aren't familiar with it (and IMHO, also even if you are). 

Is there is a (reasonable) way to provide mostly/all-CMake builds for Android? If so, we'd love to move to that for these apps.

**Comment by alexreinking** [comment] 2020-10-24 00:21
This is a duplicate of #5374

**Closed by alexreinking** 2020-10-24 00:21 UTC

**Comment by piotrklos-tcl** [comment] 2020-10-27 17:02
> This is a duplicate of #5374

I was not clear. I meant that I want an example with an Android *library* (static or shared), as opposed to a full app. I think this is an important distinction that deserves a separate example. To my knowledge it doesn't exist.
