### ISSUE TITLE
Revamp buildbots to include release-branch testing

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#5646] opened 2021-01-14 23:24 UTC
Currently our buildbots build the Halide master branch against three different LLVM versions, but ignore the Halide release branches. We need to revamp them to build the release branches too (and possibly reduce the master-branch building to offset).

Proposal:
- We currently only looks for PRs against Halide master branch; we also need to look for PRs against the Halide release branches (eg bug fixes) and run tests against those too. (These will be infrequent.)
- We currently only do 'build-a-release' builds against Halide master branch (when a change is detected); we need to do these for the release branches too. (These will be infrequent.)
- We *don't* need to look for changes in LLVM to trigger any builds. (We haven't been doing that for a while, just pointing out that we still don't.)

This brings up some interesting questions:
- We currently do most of the 'master' testing against the most recent 'stable' branch of LLVM (currently, 11), with spot-checking against trunk and one-older (12 and 10). Is this still strictly necessary? 
- While we're thinking, do we want to consider rethinking our stated policy of "3 LLVM version support" for the master branch? Now that we have releases (which correspond to an LLVM version), should we consider relaxing this somewhat (eg dropping the third-oldest), or even something more radical, like saying that 'master halide always builds against master llvm, period'? (For that last one, I suspect the answer is 'no' or at least 'not yet', but I want to throw it out there to be sure.)

Also note that https://github.com/halide/Halide/issues/5645 and https://github.com/halide/Halide/pull/5282 suggest an interesting conundrum for systems using GCC:
- For Halide 12, we will need to always build with GCC 9.x (for proper C++17 compatibility), regardless of the LLVM version we use.
- For Halide 10 and 11, we will need to continue building with GCC 7.x (to preserve compatibility for existing users)
- Thus, if we continue to build master against multiple LLVM versions, we'll have to compile LLVM10/11 using both GCC7.x and GCC9.x on those systems. (This is doable but a slight hassle and an increase in build latency and storage.)

**Comment by steven-johnson** [comment] 2021-01-14 23:25
Tagging @alexreinking and @abadams for feedback.

**Comment by alexreinking** [comment] 2021-01-14 23:45
> 'master halide always builds against master llvm, period'? (For that last one, I suspect the answer is 'no' or at least 'not yet', but I want to throw it out there to be sure.)

No, because master llvm is too volatile. I would support "master halide only builds against latest llvm release (and also master, because we have to stay on top of it)"

**Comment by steven-johnson** [comment] 2021-01-26 21:35
Is this done?

**Comment by alexreinking** [comment] 2021-01-26 23:45
Yes - I think this is a duplicate of #5549

**Closed by alexreinking** 2021-01-26 23:45 UTC
