### ISSUE TITLE
[HVX] Failure on seemingly valid schedule

### ISSUE THREAD

**Issue by rootjalex** [halide/Halide#7806] opened 2023-08-24 22:38 UTC
I'm getting a failure related to interleaving on a simple HVX schedule:
```
#include "Halide.h"
#include <iostream>
#include <stdio.h>

using namespace Halide;
using namespace Halide::ConciseCasts;

void test0() {
    Var x("x");
    ImageParam in0(UInt(8), 1);
    Target hvx("hexagon-32-noos-hvx_128-hvx_v66");
    Func out("out");
    out(x) = u8_sat(u16(in0(x)) * 5);
    out.vectorize(x, 128);
    out.compile_to_assembly("hvx-test0.asm", out.infer_arguments(), hvx);
}

int main(int arch, char **argv) {
    test0();
}
```

```
ajroot@Alexanders-MacBook-Pro Halide % ./bin/correctness_hvx
Internal Error at /Users/ajroot/projects/Halide/src/CodeGen_Hexagon.cpp:1883 triggered by user code at :
Condition failed: op->type.lanes() % (native_vector_bits() * 2 / op->type.bits()) == 0:
zsh: abort      ./bin/correctness_hvx
```

@pranavb-ca do you know what might fix this?

**Comment by pranavb-ca** [comment] 2023-08-29 04:36
Hey @rootjalex - I am sorry I missed this on Friday. Is this still an issue? Does your PR https://github.com/halide/Halide/pull/7805 fix this? Let me take a look at this on Tuesday.

**Comment by rootjalex** [comment] 2023-08-29 04:38
@pranavb-ca No worries! Unfortunately no, that PR does not address this issue

**Comment by pranavb-ca** [comment] 2023-08-29 12:10
I think I have a fix for this. This problem sounded vaguely familiar and sure enough, I had fixed this downstream recently but hadn't upstreamed my fkx. My fault entirely. Sorry about that. I'll post the fix later today (or early tomorrow if that's ok with you as I have a series of meetings today)

**Comment by rootjalex** [comment] 2023-08-29 13:45
Great, thank you so much! No rush!

**Comment by pranavb-ca** [comment] 2023-08-30 04:18
FWIW, this ``stmt`` is the probem
```
  for (out.s0.x.x, 0, out.extent.0/128) {
   out[ramp(out.s0.x.x*128, 1, 128) aligned(128, 0)] = (uint8x128)halide.hexagon.interleave.vb((uint8x128)saturating_cast((uint16x128)halide.hexagon.mpy.vub.ub(p0[ramp((out.s0.x.x*128) + (out.min.0 - p0.min.0), 1, 128)], (uint8)5)))
  }
```
``halide.hexagon.interleave.vb`` is a ``native_interleave`` as defined by CodeGen_Hexagon. So, it works only on multiples of double vectors.

The problem is that there is no saturating downcast of u16 values to u8, that is
```
u8_sat(u16)
```
isn't supported on HVX. So, the solution is to pattern match it and then custom expand it in bitcode (``hvx_128.ll``)

**Closed** 2023-09-18 19:48 UTC
