### ISSUE TITLE
a need for CMakeListst.txt in example apps

### ISSUE THREAD

**Issue by piotrklos-tcl** [halide/Halide#5398] opened 2020-10-23 14:21 UTC
A lot (probably majority) of the most important examples in the apps folder don't have CMakeLists.txt but use some other build system.

I have a problem with this, because I use cmake and it's very hard for me to use these examples to my benefit. I can't even estimate how much time or effort it will take to make an equivalent project using CMake, so I can't tell if I can use the demonstrated feature/setup.

I don't think I'm alone in this, the recent community survey shows that CMake is the most popular build system.
https://meetingcpp.com/mcpp/survey/results.php?q=39
(picture in case there are problems with the link)
![meetingcpp_survey_build_systems](https://user-images.githubusercontent.com/48292867/97014597-d299f380-154a-11eb-8280-91f435edc4a0.png)

By the way, I don't think that the Android examples can be omitted from this discussion. It's useful to have Gradle examples, but there are also people like me who are more Linux *or* library-focused, who just create a C++ project with CMake and don't want to switch to Gradle, just to cross-compile for Android.

**Comment by steven-johnson** [comment] 2020-10-23 17:04
Agree 100%. The situation is mostly historic and not deliberate -- the goal is for Halide to have CMake builds available for everything possible. (FYI, we would very much welcome contributor PRs that add missing CMake files!)

**Comment by alexreinking** [comment] 2020-10-24 00:21
This is a duplicate of #5374

**Closed by alexreinking** 2020-10-24 00:21 UTC
