### ISSUE TITLE
Is -hexagon-small-data-threshold=0 still necessary for HVX backend?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3739] opened 2019-03-18 18:28 UTC
Codegen_Hexagon currently uses `llvm::cl::ParseCommandLineOptions()` to set a command line flag (`-hexagon-small-data-threshold=0`) that affects HVX codegen; as discovered in https://github.com/halide/Halide/pull/3734, this isn't threadsafe, and could lead to unpredictable results if using Halide across multiple threads in the same process. (I'm not aware of any existing failures likely to be related to this, but it is definitely not an ideal practice.)

(1) Is this flag still necessary at recent LLVM trunk builds?
(2) Are there any other programmatic ways of getting this behavior, on a per-LLVMContext basis?
(3) If not, could such a way be added?

**Comment by steven-johnson** [comment] 2019-03-29 17:29
Gentle ping

**Comment by ronlieb** [comment] 2019-04-10 15:17
I imagine it still is needed, but ask Dan or Pranav

**Comment by steven-johnson** [comment] 2019-04-10 16:20
@pranavb-ca has never responded to this :-(

**Comment by pranavb-ca** [comment] 2019-04-10 17:19
I apologise for not responding. This fell through the cracks. My bad completely. This was put in a long time ago and i think it was needed at that time because of problems with PIC code. I am doing an experiment to see what breaks, if it does, if I remove this. I'll circle back shortly.

**Comment by dsharletg** [comment] 2019-04-11 01:12
I think this can be safely removed, after testing it on the various hexagon code we maintain.

**Comment by pranavb-ca** [comment] 2019-04-11 22:22
Agreed. I confirmed that this change did not affect any of our tests as well.
(Sorry for my delayed reply - I was out of office today)

**Comment by dsharletg** [comment] 2019-04-30 06:18
Fixed by the PR referenced above.

**Closed by dsharletg** 2019-04-30 06:18 UTC
